[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-headerpad,0x1000"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-headerpad,0x1000"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/FORCE:MULTIPLE /STACK:8388608"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-args=/FORCE:MULTIPLE /STACK:8388608"]

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
